name: release

on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: centos-latest 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: mihails-strasuns/setup-dlang@v0.3.0
        with:
          compiler: dmd-2.088.0
      - name: Build
        run: dub build --single qshow.d
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'qshow
